create schema stage;

create table stage.events(
	id serial,
	event_id  varchar null,
	event_timestamp  varchar null,
	event_type  varchar null,
	page_url  varchar null,
	page_url_path  varchar null,
	referer_url  varchar null,
	referer_url_scheme  varchar null,
	referer_url_port int4 null,
	referer_medium  varchar null,
	utm_medium  varchar null,
	utm_source  varchar null,
	utm_content  varchar null,
	utm_campaign  varchar null,
	click_id  varchar null,
	geo_latitude float null,
	geo_longitude float null,
	geo_country  varchar null,
	geo_timezone  varchar null,
	geo_region_name  varchar null,
	ip_address  varchar null,
	browser_name  varchar null,
	browser_user_agent  varchar null,
	browser_language  varchar null,
	os  varchar null,
	os_name  varchar null,
	os_timezone  varchar null,
	device_type  varchar null,
	device_is_mobile boolean null,
	user_custom_id  varchar null,
	user_domain_id  varchar null,
	CONSTRAINT events_id_pkey PRIMARY KEY (id)
);